### ISSUE TITLE
I don't know what u r doing here

### ISSUE THREAD

**Issue by LeonardoFurtado** [lubien/imgur#1]

**Comment by lubien** [comment]
Shamelessly hosting images to my bot.

![image](https://user-images.githubusercontent.com/9121359/65801658-f88a7400-e14f-11e9-8e46-462e4646a39d.png)
![image](https://user-images.githubusercontent.com/9121359/65801663-fde7be80-e14f-11e9-8211-6696dcbdb035.png)

**Comment by LeonardoFurtado** [comment]
good label

**Comment by LeonardoFurtado** [comment]
HACKTOBER FEST!

**Comment by lubien** [comment]
> HACKTOBER FEST!

Not yet lol

**Comment by lubien** [comment]
Now lemme implement binomial distribution here

**Comment by LeonardoFurtado** [comment]
SHIT

**Comment by lubien** [comment]
Tfw my code for it is on notebook and I'm on PC...
